version: "3"

services:
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - internal_network
    restart: always
    environment:
      - "POSTGRES_DB=takahe"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=insecure_password"

  web:
    build: .
    image: takahe:latest
    environment:
      - "DJANGO_SETTINGS_MODULE=takahe.settings.production"
      - "PGHOST=db"
      - "PGDATABASE=takahe"
      - "PGUSER=postgres"
      - "PGPASSWORD=insecure_password"
      - "TAKAHE_SECRET_KEY=insecure_secret"
      - "TAKAHE_MAIN_DOMAIN=example.com"
      - "TAKAHE_EMAIL_CONSOLE_ONLY=True"
      - "TAKAHE_MEDIA_BACKEND=local"
      - "TAKAHE_AUTO_ADMIN_EMAIL=admin@example.com"
    networks:
      - external_network
      - internal_network
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../:/takahe/

networks:
  internal_network:
  external_network:

volumes:
  dbdata:
